package Paquete;
import Paquete.ClaseUsuario;
import Paquete.ClaseOpcion;
/**
 * Generated by the Oracle9i JDeveloper Web Services Interface Generator
 * Date Created: Wed Feb 15 14:06:29 VET 2006
 * 
 * This interface lists the subset of public methods that you
 * selected for inclusion in your web service's public interface.
 * It is referenced in the web.xml deployment descriptor for this service.
 * 
 * This file should not be edited.
 */

public interface IClaseEnvio 
{
  public ClaseUsuario pListaOpciones(String Usuario, String Clave, String Sistema);

  public int pCambiaClave(String Usuario, String OldClave, String NewClave);
}